version: '2.2'

services:

  instant-answers:
    build:
      context: .
      dockerfile: docker/images/instant-answers/Dockerfile
    init: true
    volumes:
      - ./app:/src
    ports:
      - ${APP_PORT}:${APP_PORT}
      - ${FRONT_PORT}:${FRONT_PORT}
    depends_on:
    - iaredis
    environment:
    - APP_PORT
    - FRONT_PORT
    - ENVIRONMENT
    - REDIS_IA_HOST
    - REDIS_IA_PASSWORD
    - REDIS_IA_PORT

  iaredis:
    build:
      context: docker/images/redis
    environment:
    - REDIS_IA_HOST
    - REDIS_IA_PASSWORD
    - REDIS_IA_PORT
