var _ = require('@qwant/front-i18n')._;

module.exports = function () {
    return {
        "constants": {
            "USD": [_("dollars?", "currency_converter"), _("american dollars?", "currency_converter"), "\\$", "USD"],
            "CAD": [_("canadian dollars?", "currency_converter"), _("dollars?", "currency_converter"), "\\$", "CAD"],
            "AUD": [_("australian dollars?", "currency_converter"), _("dollars?", "currency_converter"), "\\$", "AUD"],
            "NZD": [_("new zealand dollars?", "currency_converter"), _("dollars?", "currency_converter"), "\\$", "NZD"],
            "MXN": [_("mexican pesos?", "currency_converter"), _("pesos?"), "\\$", "MXN"],
            "HKD": [_("hong kong dollars?", "currency_converter"), _("dollars?", "currency_converter"), "HK\\$", "HDK"],
            "BRL": [_("brazilian reals?", "currency_converter"), "R\\$", _("reals?", "currency_converter"), "BRL"],
            "BGN": [_("bulgarian levs?", "currency_converter"), _("levs?", "currency_converter"), "лв", "BGN"],
            "CHF": [_("swiss francs?", "currency_converter"), "CHF"],
            "JPY": [_("japanese yens?", "currency_converter"), _("yens?", "currency_converter"), "¥", "JPY"],
            "CNY": [_("chinese yuans?", "currency_converter"), _("chinese renminbis?", "currency_converter"), _("yuans?", "currency_converter"), _("renminbis?", "currency_converter"), "¥", "CNY"],
            "DKK": [_("danish krones?", "currency_converter"), _("danish crowns?", "currency_converter"), _("krones?", "currency_converter"), "kr", "DKK"],
            "SEK": [_("swedish kronas?", "currency_converter"), _("swedish kronors?", "currency_converter"), _("kronors?", "currency_converter"), _("kronas?", "currency_converter"), _("swedish crowns?", "currency_converter"), "kr", "SEK"],
            "NOK": [_("norwegian krones?", "currency_converter"), _("norwegian crowns?", "currency_converter"), _("krones?", "currency_converter"), "kr", "NOK"],
            "HRK": [_("croatian kunas?", "currency_converter"),  _("croatian crowns?", "currency_converter"), _("kunas?", "currency_converter"), "kn", "HRK"],
            "CZK": [_("czech korunas?", "currency_converter"), _("czech crowns?", "currency_converter"), _("korunas?", "currency_converter"), "Kč", "CZK"],
            "EUR": [_("euros?", "currency_converter"), "€", "EUR"],
            "GBP": [_("british pounds?", "currency_converter"), _("pounds?", "currency_converter"), _("pounds? sterlings?", "currency_converter"), _("sterlings?", "currency_converter"), "£", "GBP"],
            "HUF": [_("hungarian forints?", "currency_converter"), _("forints?", "currency_converter"), "Ft", "HUF"],
            "IDR": [_("indonesian rupiahs?"), _("rupiahs?", "currency_converter"), "Rp", "IDR"],
            "ILS": [_("israeli shekels?", "currency_converter"), _("shekels?", "currency_converter"), "₪", "ILS"],
            "INR": [_("indian rupees?", "currency_converter"), _("rupees?", "currency_converter"), "₹", "INR"],
            "KRW": [_("south korean wons?", "currency_converter"), _("korean wons?", "currency_converter"), _("wons?", "currency_converter"), "₩", "KRW"],
            "MYR": [_("malaysian ringgits?", "currency_converter"), _("ringgits?", "currency_converter"), "RM", "MYR"],
            "PHP": [_("philippine pesos?", "currency_converter"), _("pesos?", "currency_converter"), "₱", "PHP"],
            "PLN": [_("polish zlotys?", "currency_converter"), _("zlotys?", "currency_converter"), "zł", "PLN"],
            "RON": [_("romanian leus?", "currency_converter"), _("leus?", "currency_converter"), "lei", "RON"],
            "RUB": [_("russian rubles?", "currency_converter"), _("rubles?", "currency_converter"), "₽", "RUB"],
            "SGD": [_("sudanese pounds?", "currency_converter"), _("pounds?", "currency_converter"), "SD", "SGD"],
            "THB": [_("thai bahts?", "currency_converter"), _("bahts?", "currency_converter"), "฿","THB"],
            "TRY": [_("turkish liras?", "currency_converter"), _("liras?", "currency_converter"), "TRY"],
            "ZAR": [_("south african rands?", "currency_converter"), _("rands?", "currency_converter"), "R", "ZAR"]
        },

        "labels_symbols": {
            "USD": [_("US Dollar", "currency_converter"), _("US Dollars", "currency_converter"), "$"],
            "CAD": [_("Canadian Dollar", "currency_converter"), _("Canadian Dollars", "currency_converter"), "$"],
            "AUD": [_("Australian Dollar", "currency_converter"), _("Australian Dollars", "currency_converter"), "$"],
            "NZD": [_("New Zealand Dollar", "currency_converter"), _("New Zealand Dollars", "currency_converter"), "$"],
            "MXN": [_("Mexican Peso", "currency_converter"), _("Mexican Pesos", "currency_converter"), "$"],
            "HKD": [_("Hong Kong Dollar", "currency_converter"), _("Hong Kong Dollars", "currency_converter"), "HK$"],
            "BRL": [_("Brazilian Real", "currency_converter"), _("Brazilian Reals", "currency_converter"), "R$"],
            "BGN": [_("Bulgarian Lev", "currency_converter"), _("Bulgarian Levs", "currency_converter"), "лв"],
            "CHF": [_("Swiss Franc", "currency_converter"), _("Swiss Francs", "currency_converter"), "CHF"],
            "JPY": [_("Japanese Yen", "currency_converter"), _("Japanese Yens", "currency_converter"), "¥"],
            "CNY": [_("Chinese Yuan", "currency_converter"), _("Chinese Yuans", "currency_converter"), "¥"],
            "DKK": [_("Danish Krone", "currency_converter"), _("Danish Krones", "currency_converter"), "kr"],
            "SEK": [_("Swedish Krona", "currency_converter"), _("Swedish Kronas", "currency_converter"), "kr"],
            "NOK": [_("Norwegian Krone", "currency_converter"), _("Norwegian Krones", "currency_converter"), "kr"],
            "HRK": [_("Croatian Kuna", "currency_converter"), _("Croatian Kunas", "currency_converter"), "kn"],
            "CZK": [_("Czech Koruna", "currency_converter"), _("Czech Korunas", "currency_converter"), "Kč"],
            "EUR": [_("Euro", "currency_converter"), _("Euros", "currency_converter"), "€"],
            "GBP": [_("British Pound", "currency_converter"), _("British Pounds", "currency_converter"), "£"],
            "HUF": [_("Hungarian Forint", "currency_converter"), _("Hungarian Forints", "currency_converter"), "Ft"],
            "IDR": [_("Indonesian Rupiah", "currency_converter"), _("Indonesian Rupiahs", "currency_converter"), "Rp"],
            "ILS": [_("Israeli Shekel", "currency_converter"), _("Israeli Shekels", "currency_converter"), "₪"],
            "INR": [_("Indian Rupee", "currency_converter"), _("Indian Rupees", "currency_converter"), "₹"],
            "KRW": [_("South Korean Won", "currency_converter"), _("South Korean Wons", "currency_converter"), "₩"],
            "MYR": [_("Malaysian Ringgit", "currency_converter"), _("Malaysian Ringgits", "currency_converter"), "RM"],
            "PHP": [_("Philippine Peso", "currency_converter"), _("Philippine Pesos", "currency_converter"), "₱"],
            "PLN": [_("Polish Zloty", "currency_converter"), _("Polish Zlotys", "currency_converter"), "zł"],
            "RON": [_("Romanian Leu", "currency_converter"), _("Romanian Leus", "currency_converter"), "lei"],
            "RUB": [_("Russian Ruble", "currency_converter"), _("Russian Rubles", "currency_converter"), "₽"],
            "SGD": [_("Sudanese Pound", "currency_converter"), _("Sudanese Pounds", "currency_converter"), "SD"],
            "THB": [_("Thai Baht", "currency_converter"), _("Thai Bahts", "currency_converter"), "฿"],
            "TRY": [_("Turkish Lira", "currency_converter"), _("Turkish Liras", "currency_converter"), "TRY"],
            "ZAR": [_("South African Rand", "currency_converter"), _("South African Rands", "currency_converter"), "R"]
        }
    }
};