var _ = require('@qwant/front-i18n')._;

module.exports = function () {
    return {
        "fullConstant": {
            "m": _("meters", "unit converter"),
            "in": _("inches", "unit converter"),
            "ft": _("feet", "unit converter"),
            "yd": "yards",
            "mi": "miles",
            "li": "links",
            "rd": "rods",
            "ch": "chains",
            "l": "litres",
            "min": "minims",
            "fldr": "fluiddrams",
            "floz": "fluidounces",
            "gi": "gills",
            "cp": "cups",
            "pt": "pints",
            "qt": "quarts",
            "gal": "gallons",
            "bbl": "beerbarrels",
            "obl": "oilbarrels",
            "gtt": "drop",
            "rad": "radians",
            "deg": _("degrees", "unit converter"),
            "grad": "gradian",
            "arcsec": "arcseconds",
            "arcmin": "arcminutes",
            "s": _("seconds", "unit converter"),
            "Hz": "hertz",
            "g": _("grams", "unit converter"),
            "gr": "grains",
            "dram": "dram",
            "dr": "drams",
            "oz": "ounces",
            "lb": "poundmasses",
            "cwt": _("hundredweights", "unit converter"),
            "K": "kelvin",
            "degC": "celsius",
            "degF": "fahrenheit",
            "degR": "rankine",
            "mol": "moles",
            "cd": "candela",
            "N": "newton",
            "dyn": "dyne",
            "pdf": "poundforce",
            "J": "joules",
            "eV": "electronvolts",
            "W": "watts",
            "A": "amperes",
            "C": "coulombs",
            "V": "volts",
            "F": "farads",
            "Wb": "webers",
            "T": "webers",
            "H": "teslas",
            "S": "siemens",
            "b": "bits",
            "B": "bytes"
        },

        "fullPrefix": {
            "Ki": "kibi",
            "Mi": "mebi",
            "Gi": "gibi",
            "Ti": "tebi",
            "Pi": "pebi",
            "Ei": "exi",
            "Zi": "zebi",
            "Yi": "yobi",
            "da": "deca",
            "h": "hecto",
            "k": "kilo",
            "M": "mega",
            "G": "giga",
            "T": "tera",
            "P": "peta",
            "E": "exa",
            "Z": "zetta",
            "Y": "yotta",
            "d": "deci",
            "c": "centi",
            "m": "milli",
            "u": "micro",
            "n": "nano",
            "p": "pico",
            "f": "femto",
            "a": "atto",
            "z": "zepto",
            "y": "yocto"
        }
    };
};