var _ = require('@qwant/front-i18n')._;

module.exports = function () {
    return {
        "constants": [
            _("inch", "unit converter"),
            _("inches", "unit converter"),
            "in",
            _("foot", "unit converter"),
            _("feet", "unit converter"),
            "ft",
            "yard",
            "yards",
            "yd",
            "mile",
            "miles",
            "mi",
            "link",
            "links",
            "li",
            "rod",
            "rods",
            "rd",
            "chain",
            "chains",
            "ch",
            "pint",
            "pints",
            "pt",
            "quart",
            "quarts",
            "qt",
            "dram",
            "drams",
            "dr",
            "angstrom",
            "angstroms",
            "mil",
            "sqin",
            "sqft",
            "sqyd",
            "sqmi",
            "sqrd",
            "sqch",
            "sqmil",
            "cc",
            "cuin",
            "cuyd",
            _("teaspoon", "unit converter"),
            _("teaspoons", "unit converter"),
            _("tablespoon", "unit converter"),
            _("tablespoons", "unit converter"),
            "minim",
            "minims",
            "min",
            "fluiddram",
            "fluiddrams",
            "fldr",
            "fluidounce",
            "fluidounces",
            "floz",
            "gill",
            "gills",
            "gi",
            "cup",
            "cups",
            "cp",
            "gallon",
            "gallons",
            "gal",
            "beerbarrel",
            "beerbarrels",
            "bbl",
            "oilbarrel",
            "oilbarrels",
            "obl",
            "hogshead",
            "hogsheads",
            "drop",
            "gtt",
            "gtts",
            "rad",
            "radians",
            "deg",
            _("degrees", "unit converter"),
            "grad",
            "gradients",
            "cycle",
            "cycles",
            _("second", "unit converter"),
            _("seconds", "unit converter"),
            "s",
            _("minute", "unit converter"),
            _("minutes", "unit converter"),
            _("hour", "unit converter"),
            _("hours", "unit converter"),
            "h",
            _("day", "unit converter"),
            _("days", "unit converter"),
            "grain",
            "grains",
            "gr",
            "ounce",
            "ounces",
            "oz",
            "poundmass",
            "poundmasses",
            "lbm",
            "lb",
            "lbs",
            _("hundredweight", "unit converter"),
            _("hundredweights", "unit converter"),
            "cwt",
            "stick",
            "sticks",
            "stone",
            "kelvin",
            "K",
            "celsius",
            "degC",
            "fahrenheit",
            "degF",
            "rankine",
            "degR",
            "mole",
            "moles",
            "mol",
            "candela",
            "cd",
            "poundforce",
            "lbf",
            "joule",
            "joules",
            "J",
            "erg",
            "BTU",
            "hp",
            "psi",
            "atm"
        ]
    }
};