module.exports = function (i18n) {
    const _ = i18n._;
    return {
        "constants": {
            "USD": [_("dollars?", "currency_converter"), _("american dollars?", "currency_converter"), _("US dollars?", "currency_converter"), "\\$", "USD"],
            "CAD": [_("canadian dollars?", "currency_converter"), _("dollars?", "currency_converter"), "\\$", "CAD"],
            "AUD": [_("australian dollars?", "currency_converter"), _("dollars?", "currency_converter"), "\\$", "AUD"],
            "NZD": [_("new zealand dollars?", "currency_converter"), _("dollars?", "currency_converter"), "\\$", "NZD"],
            "MXN": [_("mexican pesos?", "currency_converter"), _("pesos?", "currency_converter"), "\\$", "MXN"],
            "HKD": [_("hong kong dollars?", "currency_converter"), _("dollars?", "currency_converter"), "HK\\$", "HDK"],
            "ARS": [_("Argentine Pesos?", "currency_converter"), _("pesos?", "currency_converter"), "\\$", "ARS"],
            "BMD": [_("Bermudian Dollars?", "currency_converter"), _("dollars?", "currency_converter"), "\\$", "BMD"],
            "BSD": [_("Bahamian Dollars?", "currency_converter"), _("dollars?", "currency_converter"), "\\$", "BSD"],
            "BZD": [_("Belize Dollars?", "currency_converter"), _("dollars?", "currency_converter"), "\\$", "BZD"],
            "CLP": [_("Chilean Pesos?", "currency_converter"), _("pesos?", "currency_converter"), "\\$", "CLP"],
            "COP": [_("Colombian Pesos?", "currency_converter"), _("pesos?", "currency_converter"), "\\$", "COP"],
            "CUC": [_("Cuban Convertible Pesos?", "currency_converter"), _("pesos?", "currency_converter"), "\\$", "CUC\\$", "CUC"],
            "CUP": [_("Cuban Pesos?", "currency_converter"), _("pesos?", "currency_converter"), "\\$", "\\$MN", "₱", "CUP"],
            "CVE": [_("Cape Verdean Escudos?", "currency_converter"), _("escudos?", "currency_converter"), "\\$", "Esc", "CVE"],
            "DOP": [_("Dominican Pesos?", "currency_converter"), _("pesos?", "currency_converter"), "\\$", "RD\\$", "DOP"],
            "FJD": [_("Fijian Dollars?", "currency_converter"), _("dollars?", "currency_converter"), "\\$", "FJ\\$", "FJD"],
            "GYD": [_("Guyanaese Dollars?", "currency_converter"), _("dollars?", "currency_converter"), "\\$", "G\\$", "GY$", "GYD"],
            "JMD": [_("Jamaican Dollars?", "currency_converter"), _("dollars?", "currency_converter"), "\\$", "JMD"],
            "KYD": [_("Cayman Islands Dollars?", "currency_converter"), _("dollars?", "currency_converter"), "\\$", "KYD"],
            "SGD": [_("Singapore Dollars?", "currency_converter"), _("dollars?", "currency_converter"), "\\$", "S\\$", "SGD"],
            "SBD": [_("Solomon Islands Dollars?", "currency_converter"), _("dollars?", "currency_converter"), "\\$", "SBD"],
            "SRD": [_("Surinamese Dollars?", "currency_converter"), _("dollars?", "currency_converter"), "\\$", "SRD"],
            "TTD": [_("Trinidad and Tobago Dollars?", "currency_converter"), _("dollars?", "currency_converter"), "\\$", "TT\\$", "TOP"],
            "TWD": [_("New Taiwan Dollars?", "currency_converter"), _("Taiwan Dollars?", "currency_converter"), _("dollars?", "currency_converter"), "\\$", "NT\\$", "TWD"],
            "UYU": [_("Uruguayan Pesos?", "currency_converter"), _("pesos?", "currency_converter"), "\\$", "\\$U", "UYU"],
            "XCD": [_("Eastern Caribbean dollars?", "currency_converter"), _("Caribbean dollars?", "currency_converter"), _("dollars?", "currency_converter"), "\\$", "XCD"],
            "ZWL": [_("Zimbabwean dollars?", "currency_converter"), _("dollars?", "currency_converter"), "\\$", "ZWL"],
            "BBD": [_("Barbadian Dollars?", "currency_converter"), _("dollars?", "currency_converter"), "Bds\\$", "BBD"],
            "BND": [_("Brunei Dollars?", "currency_converter"), _("dollars?", "currency_converter"), "B\\$", "BND"],
            "LRD": [_("Liberian Dollars?", "currency_converter"), _("dollars?", "currency_converter"), "L\\$", "LRD"],
            "NAD": [_("Namibian Dollars?", "currency_converter"), _("dollars?", "currency_converter"), "N\\$", "NAD"],
            "NIO": [_("Nicaraguan c(ó|o)rdobas?", "currency_converter"), _("c(ó|o)rdobas?", "currency_converter"), "C\\$", "NIO"],
            "TOP": [_("Tongan pa'anga", "currency_converter"), _("pa'anga", "currency_converter"), "T\\$", "TOP"],
            "WST": [_("Samoan t(ā|a)l(ā|a)", "currency_converter"), _("t(ā|a)l(ā|a)", "currency_converter"), "WS\\$", "SAT", "ST", "WST"],


            // Yens/Yuans
            "CNY": [_("chinese yuans?", "currency_converter"), _("chinese renminbis?", "currency_converter"), _("yuans?", "currency_converter"), _("renminbis?", "currency_converter"), "¥", "CNY"],
            "JPY": [_("japanese yens?", "currency_converter"), _("yens?", "currency_converter"), "¥", "JPY"],


            // Crowns
            "DKK": [_("danish krones?", "currency_converter"), _("danish crowns?", "currency_converter"), _("krones?", "currency_converter"), "kr", "DKK"],
            "ISK": [_("Icelandic Kr(ó|o)na", "currency_converter"), _("Icelandic Kr(ó|o)nur", "currency_converter"), _("kr(ó|o)na?", "currency_converter"), _("kr(ó|o)nur", "currency_converter"), "kr", "Íkr", "ISK"],
            "NOK": [_("norwegian krones?", "currency_converter"), _("norwegian crowns?", "currency_converter"), _("krones?", "currency_converter"), "kr", "NOK"],
            "SEK": [_("swedish kronas?", "currency_converter"), _("swedish kronors?", "currency_converter"), _("kronors?", "currency_converter"), _("kronas?", "currency_converter"), _("swedish crowns?", "currency_converter"), "kr", "SEK"],


            // Pounds
            "GBP": [_("british pounds?", "currency_converter"), _("pounds?", "currency_converter"), _("pounds? sterlings?", "currency_converter"), _("sterlings?", "currency_converter"), "£", "GBP"],
            "EGP": [_("Egyptian Pounds?", "currency_converter"), _("pounds?", "currency_converter"), "E£", "EGP"],
            "FKP": [_("Falkland Islands Pounds?", "currency_converter"), _("pounds?", "currency_converter"), "£", "FKP"],
            "GGP": [_("Guernsey Pounds?", "currency_converter"), _("pounds?", "currency_converter"), "£", "GGP"],
            "GIP": [_("Gibraltar Pounds?", "currency_converter"), _("pounds?", "currency_converter"), "£", "GIP"],
            "IMP": [_("Manx pounds?", "currency_converter"), _("pounds?", "currency_converter"), "£", "IMP"],
            "JEP": [_("Jersey Pounds?", "currency_converter"), _("pounds?", "currency_converter"), "£", "IMP"],
            "LBP": [_("Lebanese Pounds?", "currency_converter"), _("pounds?", "currency_converter"), "LL", "LBP"],
            "SDG": [_("sudanese pounds?", "currency_converter"), _("pounds?", "currency_converter"), "SD", "SDG"],
            "SHP": [_("Saint Helena Pounds?", "currency_converter"), _("pounds?", "currency_converter"), "£", "SHP"],
            "SYP": [_("Syrian Pounds?", "currency_converter"), _("pounds?", "currency_converter"), "LS", "£S", "SYP"],

            // Rupees
            "INR": [_("indian rupees?", "currency_converter"), _("rupees?", "currency_converter"), "₹", "INR"],
            "IDR": [_("indonesian rupiahs?", "currency_converter"), _("rupiahs?", "currency_converter"), "Rp", "IDR"],
            "PKR": [_("Pakistani Rupees?", "currency_converter"), _("rupees?", "currency_converter"), "₨", "Rs", "PKR"],
            "LKR": [_("Sri Lankan Rupees?", "currency_converter"), _("rupees?", "currency_converter"), "Rs", "LKR"],
            "MUR": [_("Mauritian Rupees?", "currency_converter"), _("rupees?", "currency_converter"), "₨", "Rs", "MUR"],
            "NPR": [_("Nepalese Rupees?", "currency_converter"), _("Nepalese Rupees?", "currency_converter"), "रु", "Rs\.", "Re\.", "NPR"],

            // Ambiguous
            "RUB": [_("russian rubles?", "currency_converter"), _("rubles?", "currency_converter"), "₽", "RUB"],
            "BYN": [_("New Belarusian Rubles?", "currency_converter"), _("belarusian rubles?", "currency_converter"), _("rubles?", "currency_converter"), "Br", "BYN"],
            "ETB": [_("Ethiopian Birrs?", "currency_converter"), _("birrs?", "currency_converter"), "Br", "ETB"],

            "SAR": [_("Saudi riyals?", "currency_converter"), _("riyals?", "currency_converter"), "SR", "SAR"],
            "SCR": [_("Seychellois Rupees?", "currency_converter"), _("rupees?", "currency_converter"), "SR", "SRe", "SCR"],


            "AED": [_("United Arab Emirates Dirhams?", "currency_converter"), _("dirhams?", "currency_converter"), "DH", "AED"],
            "AFN": [_("Afghan Afghanis?", "currency_converter"), _("Afghanis?", "currency_converter"), "؋", "Afs?", "AFN"],
            "ALL": [_("Albanian Leks?", "currency_converter"), _("Leks?", "currency_converter"), "lekë", "ALL"],
            "AMD": [_("Armenian Drams?", "currency_converter"), _("Drams?", "currency_converter"), "֏", "AMD"],
            "ANG": [_("Netherlands Antillean Guilders?", "currency_converter"), _("Guilders?", "currency_converter"), "ANG"],
            "AOA": [_("Angolan Kwanzas?", "currency_converter"), _("kwanzas?", "currency_converter"), "Kz", "AOA"],
            "AWG": [_("Aruban Florins?", "currency_converter"), _("florins?", "currency_converter"), "Afl\.", "AWG"],
            "AZN": [_("Azerbaijani Manats?", "currency_converter"), _("manats?", "currency_converter"), "₼", "AZN"],
            "BAM": [_("Bosnia-Herzegovina Convertible Marks?", "currency_converter"), _("Marks?", "currency_converter"), "KM", "BAM"],
            "BDT": [_("Bangladeshi Takas?", "currency_converter"), _("takas?", "currency_converter"), "৳", "BDT"],
            "BGN": [_("bulgarian levs?", "currency_converter"), _("levs?", "currency_converter"), "лв", "BGN"],
            "BHD": [_("Bahraini Dinars?", "currency_converter"), _("dinars?", "currency_converter"), "BD", "BHD"],
            "CHF": [_("swiss francs?", "currency_converter"), _("francs?", "currency_converter"), "CHF"],
            "BIF": [_("Burundian Francs?", "currency_converter"), _("francs?", "currency_converter"), "FBu", "BIF"],
            "BOB": [_("Bolivian Bolivianos?", "currency_converter"), _("bolivianos?", "currency_converter"), "Bs\.", "Bs", "BOB"],
            "BRL": [_("brazilian reals?", "currency_converter"), "R\\$", _("reals?", "currency_converter"), "BRL"],
            "BTC": [_("Bitcoins?", "currency_converter"), "₿", "XBT", "BTC"],
            "BTN": [_("Bhutanese Ngultrums?", "currency_converter"), _("ngultrums?", "currency_converter"), "Nu\.", "Nu", "BTN"],
            "BWP": [_("Botswana Pulas?", "currency_converter"), _("pulas?", "currency_converter"), "BWP"],
            "CDF": [_("Congolese Francs?", "currency_converter"), _("francs?", "currency_converter"), "FC", "CDF"],
            "CLF": [_("Chilean Units? of Account", "currency_converter"), _("Unidad(es)? de Fomento", "currency_converter"), "UF", "CLF"],
            "CRC": [_("Costa Rican Col(ó|o)n(es)?", "currency_converter"), _("col(ó|o)n(es)?", "currency_converter"), "₡", "CRC"],
            "CZK": [_("czech korunas?", "currency_converter"), _("czech crowns?", "currency_converter"), _("korunas?", "currency_converter"), "Kč", "CZK"],
            "DJF": [_("Djiboutian Francs?", "currency_converter"), _("francs?", "currency_converter"), "Fdj", "DJF"],
            "DZD": [_("Algerian Dinars?", "currency_converter"), _("dinars?", "currency_converter"), "DA", "DZD"],
            "ERN": [_("Eritrean Nakfas?", "currency_converter"), _("nafkas?", "currency_converter"), "Nfk", "ERN"],
            "EUR": [_("euros?", "currency_converter"), "€", "EUR"],
            "GEL": [_("Georgian Laris?", "currency_converter"), _("laris?", "currency_converter"), "ლ", "GEL"],
            "GHS": [_("Ghanaian Cedis?", "currency_converter"), _("cedis?", "currency_converter"), "GH₵", "GH¢", "GHS"],
            "GMD": [_("Gambian Dalasis?", "currency_converter"), _("dalasis?", "currency_converter"), "GMD"],
            "GNF": [_("Guinean Francs?", "currency_converter"), _("francs?", "currency_converter"), "FG", "GNF"],
            "GTQ": [_("Guatemalan Quetzals?", "currency_converter"), _("quetzals?", "currency_converter"), "GTQ"],
            "HNL": [_("Honduran Lempiras?", "currency_converter"), _("lempiras?", "currency_converter"), "HNL"],
            "HRK": [_("croatian kunas?", "currency_converter"),  _("croatian crowns?", "currency_converter"), _("kunas?", "currency_converter"), "kn", "HRK"],
            "HTG": [_("Haitian Gourdes?", "currency_converter"), _("groudes?", "currency_converter"), "HTG"],
            "HUF": [_("hungarian forints?", "currency_converter"), _("forints?", "currency_converter"), "Ft", "HUF"],
            "ILS": [_("israeli shekels?", "currency_converter"), _("shekels?", "currency_converter"), "₪", "ILS"],
            "IQD": [_("Iraqi Dinars?", "currency_converter"), _("dinars?", "currency_converter"), "IQD"],
            "IRR": [_("Iranian Rials?", "currency_converter"), _("rials?", "currency_converter"), "IRR"],
            "JOD": [_("Jordanian Dinars?", "currency_converter"), _("dinars?", "currency_converter"), "JOD"],
            "KES": [_("Kenyan Shillings?", "currency_converter"), _("shillings?", "currency_converter"), "KSh", "KES"],
            "KGS": [_("Kyrgystani Soms?", "currency_converter"), _("soms?", "currency_converter"), "KGS"],
            "KHR": [_("Cambodian Riels?", "currency_converter"), _("riels?", "currency_converter"), "៛", "KHR"],
            "KMF": [_("Comorian Francs?", "currency_converter"), _("francs?", "currency_converter"), "CF", "KMF"],
            "KPW": [_("North Korean Wons?", "currency_converter"), _("wons?", "currency_converter"), "₩", "KPW"],
            "KRW": [_("south korean wons?", "currency_converter"), _("korean wons?", "currency_converter"), _("wons?", "currency_converter"), "₩", "KRW"],
            "KWD": [_("Kuwaiti Dinars?", "currency_converter"), _("dinars?", "currency_converter"), "KD", "KWD"],
            "KZT": [_("Kazakhstani Te(n|ń)ge", "currency_converter"), _("te(n|ń)ge", "currency_converter"), "₸", "KZT"],
            "LAK": [_("Laotian Kips?", "currency_converter"), _("lao kips?", "currency_converter"), _("kips?", "currency_converter"), "₭", "₭N", "LAK"],
            "LSL": [_("Lesotho (ma)?Loti", "currency_converter"), _("(ma)?loti", "currency_converter"), "LSL"],
            "LTL": [_("Lithuanian Litai?", "currency_converter"), _("litai?", "currency_converter"), "Lt", "LTL"],
            "LYD": [_("Libyan Dinars?", "currency_converter"), _("dinars?", "currency_converter"), "LD", "LYD"],
            "MAD": [_("Moroccan Dirhams?", "currency_converter"), _("dirhams?", "currency_converter"), "DH", "MAD"],
            "MDL": [_("Moldovan Le(u|i)", "currency_converter"), _("le(u|i)", "currency_converter"), "MDL"],
            "MGA": [_("Malagasy Ariary", "currency_converter"), _("ariary", "currency_converter"), "Ar", "MGA"],
            "MKD": [_("Macedonian Denar(i|s)?", "currency_converter"), _("denar(i|s)?", "currency_converter"), "den", "MKD"],
            "MMK": [_("Myanma Kyats?", "currency_converter"), _("Burmese kyats?", "currency_converter"), _("kyats?", "currency_converter"), "MMK"],
            "MNT": [_("Mongolian tögrög|tugrik", "currency_converter"), _("tögrög|tugrik", "currency_converter"), "₮", "MNT"],
            "MOP": [_("Macanese Patacas?", "currency_converter"), _("patacas?", "currency_converter"), "MOP\\$", "MOP"],
            "MRO": [_("Mauritanian Ougu?iyas?", "currency_converter"), _("Ougu?iyas?", "currency_converter"), "UM", "MRO"],
            "MVR": [_("Maldivian Rufiyaas?", "currency_converter"), _("rufiyaas?", "currency_converter"), "MRf", "Rf", "MVR"],
            "MWK": [_("Malawi(an)? kwachas?", "currency_converter"), _("kwachas?", "currency_converter"), "MK", "MWK"],
            "MYR": [_("malaysian ringgits?", "currency_converter"), _("ringgits?", "currency_converter"), "RM", "MYR"],
            "MZN": [_("Mozambican Meticals?", "currency_converter"), _("meticals?", "currency_converter"), "MT", "MZN"],
            "NGN": [_("Nigerian Naira", "currency_converter"), _("naira", "currency_converter"), "₦", "NGN"],
            "OMR": [_("Omani Rials?", "currency_converter"), _("rials?", "currency_converter"), "OMR"],
            "PAB": [_("Panamanian Balboas?", "currency_converter"), _("balboas?", "currency_converter"), "B\/\.", "PAB"],
            "PEN": [_("Peruvian Nuevo Sol(es)?", "currency_converter"), _("sol(es)?", "currency_converter"), "S\/", "PEN"],
            "PGK": [_("Papua New Guinean Kina", "currency_converter"), _("kina", "currency_converter"), "PGK"],
            "PHP": [_("philippine pesos?", "currency_converter"), _("pesos?", "currency_converter"), "₱", "PHP"],
            "PLN": [_("polish z(l|ł)otys?", "currency_converter"), _("z(l|ł)otys?", "currency_converter"), "zł", "PLN"],
            "PYG": [_("Paraguayan guaran(í|i)?(es)?", "currency_converter"), _("guaran(í|i)?(es)?", "currency_converter"), "₲", "PYG"],
            "QAR": [_("Qatari Riyals?", "currency_converter"), _("riyals?", "currency_converter"), "QR", "QAR"],
            "RON": [_("romanian le(u|i)", "currency_converter"), _("le(u|i)", "currency_converter"), "lei", "RON"],
            "RSD": [_("Serbian Dinars?", "currency_converter"), _("dinars?", "currency_converter"), "din", "RSD"],
            "RWF": [_("Rwandan Francs?", "currency_converter"), _("francs?", "currency_converter"), "FRw", "RF", "R₣", "RWF"],
            "SLL": [_("Sierra Leonean leones?", "currency_converter"), _("leones?", "currency_converter"), "SLL"],
            "SOS": [_("Somali Shillings?", "currency_converter"), _("shillings?", "currency_converter"), "Sh", "So", "SOS"],
            "STN": [_("S(ã|a)o Tom(é|e) and Pr(í|i)ncipe dobras?", "currency_converter"), _("dobras?", "currency_converter"), "Db", "STN"],
            "SVC": [_("Salvadoran Col(ó|o)n(es)?", "currency_converter"), _("col(ó|o)n(es)?", "currency_converter"), "₡", "SVC"],
            "SZL": [_("Swazi (lilangeni|emalangeni)", "currency_converter"), _("(lilangeni|emalangeni)", "currency_converter"), "SZL"],
            "THB": [_("thai bahts?", "currency_converter"), _("bahts?", "currency_converter"), "฿","THB"],
            "TJS": [_("Tajikistani Somoni", "currency_converter"), _("somoni", "currency_converter"), "TJS"],
            "TMT": [_("Turkmenistan manats?", "currency_converter"), _("manats?", "currency_converter"), "TMT"],
            "TND": [_("Tunisian Dinars?", "currency_converter"), _("dinars?", "currency_converter"), "DT", "TND"],
            "TRY": [_("turkish liras?", "currency_converter"), _("liras?", "currency_converter"), "TRY"],
            "TZN": [_("Tanzanian Shillings?", "currency_converter"), _("shillings?", "currency_converter"), "TSh", "TZN"],
            "UAH": [_("Ukrainian Hryvnia", "currency_converter"), _("Hryvnia", "currency_converter"), "₴", "UAH"],
            "UGX": [_("Ugandan Shillings?", "currency_converter"), _("shillings?", "currency_converter"), "USh", "UGX"],
            "UZS": [_("Uzbekistan So'?ms?", "currency_converter"), _("so'?ms?", "currency_converter"), "UZS"],
            "VEF": [_("Venezuelan Bol(í|i)var(es)?( fuertes?)?", "currency_converter"), _("Bol(í|i)var(es)?( fuertes?)?", "currency_converter"), "Bs\.F\.", "Bs\.", "VEF"],
            "VND": [_("Vietnamese (đ|d|Đ)(ồ|o)ng", "currency_converter"), _("(đ|d|Đ)(ồ|o)ng", "currency_converter"), "₫", "VND"],
            "VUV": [_("Vanuatu Vatu", "currency_converter"), _("vatu", "currency_converter"), "VT", "VUV"],
            "XAF": [_("CFA francs?", "currency_converter"), "FCFA", "XAF"],
            "XAG": [_("(Troy )?ounces? of silver", "currency_converter"), "XAG"],
            "XAU": [_("(Troy )?ounces? of gold", "currency_converter"), "XAU"],
            "XDR": [_("Special drawing rights", "currency_converter"), _("SDR", "currency_converter"), "XDR"],
            "XOF": [_("CFA francs?", "currency_converter"), "CFA", "XOF"],
            "XPF": [_("CFP francs?", "currency_converter"), "CFP", "XPF"],
            "YER": [_("Yemeni riy?als?", "currency_converter"), _("riy?als?", "currency_converter"), "YER"],
            "ZAR": [_("south african rands?", "currency_converter"), _("rands?", "currency_converter"), "ZAR"],
            "ZMW": [_("Zambian kwachas?", "currency_converter"), _("kwachas?", "currency_converter"), "ZK", "ZMW"],
        },

        "labels_symbols": {
            // Dollars
            "USD": [_("American Dollar", "currency_converter"), _("American Dollars", "currency_converter"), "$"],
            "CAD": [_("Canadian Dollar", "currency_converter"), _("Canadian Dollars", "currency_converter"), "$"],
            "AUD": [_("Australian Dollar", "currency_converter"), _("Australian Dollars", "currency_converter"), "$"],
            "NZD": [_("New Zealand Dollar", "currency_converter"), _("New Zealand Dollars", "currency_converter"), "$"],
            "MXN": [_("Mexican Peso", "currency_converter"), _("Mexican Pesos", "currency_converter"), "$"],
            "HKD": [_("Hong Kong Dollar", "currency_converter"), _("Hong Kong Dollars", "currency_converter"), "HK$"],
            "ARS": [_("Argentine Peso", "currency_converter"), _("Argentine Pesos", "currency_converter"), "$"],
            "BMD": [_("Bermudian Dollar", "currency_converter"), _("Bermudian Dollars", "currency_converter"), "$"],
            "BSD": [_("Bahamian Dollar", "currency_converter"), _("Bahamian Dollars", "currency_converter"), "$"],
            "BZD": [_("Belize Dollar", "currency_converter"), _("Belize Dollars", "currency_converter"), "$"],
            "CLP": [_("Chilean Peso", "currency_converter"), _("Chilean Pesos", "currency_converter"), "$"],
            "COP": [_("Colombian Peso", "currency_converter"), _("Colombian Pesos", "currency_converter"), "$"],
            "CUC": [_("Cuban Convertible Peso", "currency_converter"), _("Cuban Convertible Pesos", "currency_converter"), "$"],
            "CUP": [_("Cuban Peso", "currency_converter"), _("Cuban Pesos", "currency_converter"), "$"],
            "CVE": [_("Cape Verdean Escudo", "currency_converter"), _("Cape Verdean Escudos", "currency_converter"), "$"],
            "DOP": [_("Dominican Peso", "currency_converter"), _("Dominican Pesos", "currency_converter"), "$"],
            "FJD": [_("Fijian Dollar", "currency_converter"), _("Fijian Dollars", "currency_converter"), "$"],
            "GYD": [_("Guyanaese Dollar", "currency_converter"), _("Guyanaese Dollars", "currency_converter"), "$"],
            "JMD": [_("Jamaican Dollar", "currency_converter"), _("Jamaican Dollars", "currency_converter"), "$"],
            "KYD": [_("Cayman Islands Dollar", "currency_converter"), _("Cayman Islands Dollars", "currency_converter"), "$"],
            "SGD": [_("Singapore Dollar", "currency_converter"), _("Singapore Dollars", "currency_converter"), "$"],
            "SBD": [_("Solomon Islands Dollar", "currency_converter"), _("Solomon Islands Dollars", "currency_converter"), "$"],
            "SRD": [_("Surinamese Dollar", "currency_converter"), _("Surinamese Dollars", "currency_converter"), "$"],
            "TTD": [_("Trinidad and Tobago Dollar", "currency_converter"), _("Trinidad and Tobago Dollars", "currency_converter"), "$"],
            "TWD": [_("New Taiwan Dollar", "currency_converter"), _("New Taiwan Dollars", "currency_converter"), "$"],
            "UYU": [_("Uruguayan Peso", "currency_converter"), _("Uruguayan Pesos", "currency_converter"), "$"],
            "XCD": [_("Eastern Caribbean Dollar", "currency_converter"), _("Eastern Caribbean Dollars", "currency_converter"), "$"],
            "ZWL": [_("Zimbabwean Dollar", "currency_converter"), _("Zimbabwean Dollars", "currency_converter"), "$"],
            "BBD": [_("Barbadian Dollar", "currency_converter"), _("Barbadian Dollars", "currency_converter"), "Bds$"],
            "BND": [_("Brunei Dollar", "currency_converter"), _("Brunei Dollars", "currency_converter"), "B$"],
            "BRL": [_("Brazilian Real", "currency_converter"), _("Brazilian Reals", "currency_converter"), "R$"],
            "LRD": [_("Liberian Dollar", "currency_converter"), _("Liberian Dollars", "currency_converter"), "L$"],
            "NAD": [_("Namibian Dollar", "currency_converter"), _("Namibian Dollars", "currency_converter"), "N$"],
            "NIO": [_("Nicaraguan Córdoba", "currency_converter"), _("Nicaraguan Córdobas", "currency_converter"), "C$"],
            "TOP": [_("Tongan Pa'anga", "currency_converter"), _("Tongan Pa'anga", "currency_converter"), "T$"],
            "WST": [_("Samoan Tālā", "currency_converter"), _("Samoan Tālā", "currency_converter"), "WS$"],

            // Yens/Yuans
            "CNY": [_("Chinese Yuan", "currency_converter"), _("Chinese Yuans", "currency_converter"), "¥"],
            "JPY": [_("Japanese Yen", "currency_converter"), _("Japanese Yens", "currency_converter"), "¥"],

            // Crowns
            "DKK": [_("Danish Krone", "currency_converter"), _("Danish Krones", "currency_converter"), "kr"],
            "ISK": [_("Icelandic Króna", "currency_converter"), _("Icelandic Krónur", "currency_converter"),"kr"],
            "NOK": [_("Norwegian Krone", "currency_converter"), _("Norwegian Krones", "currency_converter"), "kr"],
            "SEK": [_("Swedish Krona", "currency_converter"), _("Swedish Kronors", "currency_converter"), "kr"],

            // Pounds
            "GBP": [_("British Pound", "currency_converter"), _("British Pounds", "currency_converter"), "£"],
            "EGP": [_("Egyptian Pound", "currency_converter"), _("Egyptian Pounds", "currency_converter"), "E£"],
            "FKP": [_("Falkland Islands Pound", "currency_converter"), _("Falkland Islands Pounds", "currency_converter"), "£"],
            "GGP": [_("Guernsey Pound", "currency_converter"), _("Guernsey Pounds", "currency_converter"), "£"],
            "GIP": [_("Gibraltar Pound", "currency_converter"), _("Gibraltar Pounds", "currency_converter"), "£"],
            "IMP": [_("Manx Pound", "currency_converter"), _("Manx Pounds", "currency_converter"), "£"],
            "JEP": [_("Jersey Pound", "currency_converter"), _("Jersey Pounds", "currency_converter"), "£"],
            "LBP": [_("Lebanese Pound", "currency_converter"), _("Lebanese Pounds", "currency_converter"), "LL"],
            "SDG": [_("Sudanese Pound", "currency_converter"), _("Sudanese Pounds", "currency_converter"), "SD"],
            "SHP": [_("Saint Helena Pound", "currency_converter"), _("Saint Helena Pounds", "currency_converter"), "£"],
            "SYP": [_("Syrian Pound", "currency_converter"), _("Syrian Pounds", "currency_converter"), "£S"],

            // Ambiguous
            "BYN": [_("New Belarusian Ruble", "currency_converter"), _("New Belarusian Rubles", "currency_converter"), "Br"],
            "ETB": [_("Ethiopian Birr", "currency_converter"), _("Ethiopian Birrs", "currency_converter"), "Br"],

            "SAR": [_("Saudi Riyal", "currency_converter"), _("Saudi Riyals", "currency_converter"), "SR"],
            "SCR": [_("Seychellois Rupee", "currency_converter"), _("Seychellois Rupees", "currency_converter"), "SR"],

            "AED": [_("United Arab Emirates Dirham", "currency_converter"), _("United Arab Emirates Dirhams", "currency_converter"), "DH"],
            "AFN": [_("Afghan Afghani", "currency_converter"), _("Afghan Afghanis", "currency_converter"), "؋"],
            "ALL": [_("Albanian Lek", "currency_converter"), _("Albanian Leks", "currency_converter"), "lekë"],
            "AMD": [_("Armenian Dram", "currency_converter"), _("Armenian Dram", "currency_converter"), "֏"],
            "ANG": [_("Netherlands Antillean Guilder", "currency_converter"), _("Netherlands Antillean Guilder", "currency_converter"), "ƒ"],
            "AOA": [_("Angolan Kwanza", "currency_converter"), _("Angolan Kwanzas", "currency_converter"), "Kz"],
            "AWG": [_("Aruban Florin", "currency_converter"), _("Aruban Florins", "currency_converter"), "Afl\."],
            "AZN": [_("Azerbaijani Manat", "currency_converter"), _("Azerbaijani Manats", "currency_converter"), "₼"],
            "BAM": [_("Bosnia-Herzegovina Convertible Mark", "currency_converter"), _("Bosnia-Herzegovina Convertible Marks", "currency_converter"), "KM"],
            "BDT": [_("Bangladeshi Taka", "currency_converter"), _("Bangladeshi Takas", "currency_converter"), "৳"],
            "BGN": [_("Bulgarian Lev", "currency_converter"), _("Bulgarian Levs", "currency_converter"), "лв"],
            "BHD": [_("Bahraini Dinar", "currency_converter"), _("Bahraini Dinars", "currency_converter"), "BD"],
            "BIF": [_("Burundian Franc", "currency_converter"), _("Burundian Francs", "currency_converter"), "FBu"],
            "BOB": [_("Bolivian Bolivianos", "currency_converter"), _("Bolivian Bolivianos", "currency_converter"), "Bs\."],
            "BTC": [_("Bitcoin", "currency_converter"), _("Bitcoins", "currency_converter"), "₿"],
            "BTN": [_("Bhutanese Ngultrum", "currency_converter"), _("Bhutanese Ngultrums", "currency_converter"), "Nu\."],
            "BWP": [_("Botswana Pula", "currency_converter"), _("Botswana Pulas", "currency_converter")],
            "CDF": [_("Congolese Franc", "currency_converter"), _("Congolese Francs", "currency_converter"), "FC"],
            "CHF": [_("Swiss Franc", "currency_converter"), _("Swiss Francs", "currency_converter"), "CHF"],
            "CLF": [_("Chilean Units of Account", "currency_converter"), _("Chilean Unit of Account", "currency_converter"), "UF"],
            "CRC": [_("Costa Rican Colón", "currency_converter"), _("Costa Rican Colónes", "currency_converter"), "₡"],
            "CZK": [_("Czech Koruna", "currency_converter"), _("Czech Korunas", "currency_converter"), "Kč"],
            "DJF": [_("Djiboutian Franc", "currency_converter"), _("Djiboutian Francs", "currency_converter"), "Fdj"],
            "DZD": [_("Algerian Dinar", "currency_converter"), _("Algerian Dinars", "currency_converter"), "DA"],
            "ERN": [_("Eritrean Nakfa", "currency_converter"), _("Eritrean Nakfas", "currency_converter"), "Nfk"],
            "EUR": [_("Euro", "currency_converter"), _("Euros", "currency_converter"), "€"],
            "GEL": [_("Georgian Lari", "currency_converter"), _("Georgian Laris", "currency_converter"), "ლ"],
            "GHS": [_("Ghanaian Cedi", "currency_converter"), _("Ghanaian Cedis", "currency_converter"), "GH₵"],
            "GMD": [_("Gambian Dalasi", "currency_converter"), _("Gambian Dalasis", "currency_converter")],
            "GNF": [_("Guinean Franc", "currency_converter"), _("Guinean Francs", "currency_converter"), "FG"],
            "GTQ": [_("Guatemalan Quetzal", "currency_converter"), _("Guatemalan Quetzals", "currency_converter")],
            "HNL": [_("Honduran Lempira", "currency_converter"), _("Honduran Lempiras", "currency_converter"), "HNL"],
            "HRK": [_("Croatian Kuna", "currency_converter"),  _("Croatian Kunas", "currency_converter"), "kn"],
            "HTG": [_("Haitian Gourde", "currency_converter"), _("Haitian Gourdes", "currency_converter")],
            "HUF": [_("Hungarian Forint", "currency_converter"), _("Hungarian Forints", "currency_converter"), "Ft"],
            "IDR": [_("Indonesian Rupiah", "currency_converter"), _("Indonesian Rupiahs", "currency_converter"), "Rp"],
            "ILS": [_("Israeli Shekel", "currency_converter"), _("Israeli Shekels", "currency_converter"), "₪"],
            "INR": [_("Indian Rupee", "currency_converter"), _("Indian Rupees", "currency_converter"), "₹"],
            "IQD": [_("Iraqi Dinar", "currency_converter"), _("Iraqi Dinars", "currency_converter"), "IQD"],
            "IRR": [_("Iranian Rial", "currency_converter"), _("Iranian Rials", "currency_converter"), "IRR"],
            "JOD": [_("Jordanian Dinar", "currency_converter"), _("Jordanian Dinars", "currency_converter"), "JOD"],
            "KES": [_("Kenyan Shilling", "currency_converter"), _("Kenyan Shillings", "currency_converter"), "KSh"],
            "KGS": [_("Kyrgystani Som", "currency_converter"), _("Kyrgystani Soms", "currency_converter"), "KGS"],
            "KHR": [_("Cambodian Riel", "currency_converter"), _("Cambodian Riels", "currency_converter"), "៛"],
            "KMF": [_("Comorian Francs", "currency_converter"), _("Comorian Francs", "currency_converter"), "CF"],
            "KPW": [_("North Korean Won", "currency_converter"), _("North Korean Wons", "currency_converter"), "₩"],
            "KRW": [_("South Korean Won", "currency_converter"), _("South Korean Wons", "currency_converter"), "₩"],
            "KWD": [_("Kuwaiti Dinar", "currency_converter"), _("Kuwaiti Dinars", "currency_converter"), "KD"],
            "KZT": [_("Kazakhstani Teńge", "currency_converter"), _("Kazakhstani Teńge", "currency_converter"), "₸"],
            "LAK": [_("Laotian Kip", "currency_converter"), _("Laotian Kips", "currency_converter"), "₭"],
            "LKR": [_("Sri Lankan Rupee", "currency_converter"), _("Sri Lankan Rupees", "currency_converter"), "Rs"],
            "LSL": [_("Lesotho Loti", "currency_converter"), _("Lesotho Maloti", "currency_converter"), "LSL"],
            "LTL": [_("Lithuanian Lita", "currency_converter"), _("Lithuanian Litai", "currency_converter"), "Lt"],
            "LYD": [_("Libyan Dinar", "currency_converter"), _("Libyan Dinars", "currency_converter"), "LD"],
            "MAD": [_("Moroccan Dirham", "currency_converter"), _("Moroccan Dirhams", "currency_converter"), "DH"],
            "MDL": [_("Moldovan Leu", "currency_converter"), _("Moldovan Lei", "currency_converter"), "MDL"],
            "MGA": [_("Malagasy Ariary", "currency_converter"), _("Malagasy Ariary", "currency_converter"), "Ar"],
            "MKD": [_("Macedonian Denar", "currency_converter"), _("Macedonian Denari", "currency_converter"), "den"],
            "MMK": [_("Myanma Kyat", "currency_converter"), _("Myanma Kyats", "currency_converter")],
            "MNT": [_("Mongolian Tögrög", "currency_converter"), _("Mongolian Tugrik", "currency_converter"), "₮"],
            "MOP": [_("Macanese Pataca", "currency_converter"), _("Macanese Patacas", "currency_converter"), "MOP$"],
            "MRO": [_("Mauritanian Ougiya (1973-2017)", "currency_converter"), _("Mauritanian Ougiyas (1973-2017)", "currency_converter"), "UM"],
            "MUR": [_("Mauritian Rupee", "currency_converter"), _("Mauritian Rupees", "currency_converter"), "₨"],
            "MVR": [_("Maldivian Rufiyaa", "currency_converter"), _("Maldivian Rufiyaas", "currency_converter"), "MRf"],
            "MWK": [_("Malawi Kwacha", "currency_converter"), _("Malawi Kwachas", "currency_converter"), "MK"],
            "MYR": [_("Malaysian Ringgit", "currency_converter"), _("Malaysian Ringgits", "currency_converter"), "RM"],
            "MZN": [_("Mozambican Metical", "currency_converter"), _("Mozambican Meticals", "currency_converter"), "MT"],
            "NGN": [_("Nigerian Naira", "currency_converter"), _("Nigerian Naira", "currency_converter"), "₦"],
            "NPR": [_("Nepalese Rupee", "currency_converter"), _("Nepalese Rupees", "currency_converter"), "रु"],
            "OMR": [_("Omani Rial", "currency_converter"), _("Omani Rials", "currency_converter"), "OMR"],
            "PAB": [_("Panamanian Balboa", "currency_converter"), _("Panamanian Balboas", "currency_converter"), "B/\."],
            "PEN": [_("Peruvian Nuevo Sol", "currency_converter"), _("Peruvian Nuevo Soles", "currency_converter"), "S/"],
            "PGK": [_("Papua New Guinean Kina", "currency_converter"), _("Papua New Guinean Kina", "currency_converter")],
            "PHP": [_("Philippine Peso", "currency_converter"), _("Philippine Pesos", "currency_converter"), "₱"],
            "PKR": [_("Pakistani Rupee", "currency_converter"), _("Pakistani Rupees", "currency_converter"), "₨"],
            "PLN": [_("Polish Złoty", "currency_converter"), _("Polish Złotys", "currency_converter"), "zł"],
            "PYG": [_("Paraguayan Guaraní", "currency_converter"), _("Paraguayan Guaraníes", "currency_converter"), "₲"],
            "QAR": [_("Qatari Riyal", "currency_converter"), _("Qatari Riyals", "currency_converter"), "QR"],
            "RON": [_("Romanian Leu", "currency_converter"), _("Romanian Leus", "currency_converter"), "lei"],
            "RSD": [_("Serbian Dinar", "currency_converter"), _("Serbian Dinars", "currency_converter"), "din"],
            "RUB": [_("Russian Ruble", "currency_converter"), _("Russian Rubles", "currency_converter"), "₽"],
            "RWF": [_("Rwandan Franc", "currency_converter"), _("Rwandan Francs", "currency_converter"), "FRw"],
            "SLL": [_("Sierra Leonean Leone", "currency_converter"), _("Sierra Leonean Leones", "currency_converter"), "Le"],
            "SOS": [_("Somali Shilling", "currency_converter"), _("Somali Shillings", "currency_converter"), "Sh"],
            "STN": [_("São Tomé and Príncipe Dobra", "currency_converter"), _("São Tomé and Príncipe Dobras", "currency_converter"), "Db"],
            "SVC": [_("Salvadoran Colón", "currency_converter"), _("Salvadoran Colónes", "currency_converter"), "₡"],
            "SZL": [_("Swazi Lilangeni", "currency_converter"), _("Swazi Emalangeni", "currency_converter"), "SZL"],
            "THB": [_("Thai Baht", "currency_converter"), _("Thai Bahts", "currency_converter"), "฿"],
            "TJS": [_("Tajikistani Somoni", "currency_converter"), _("Tajikistani Somoni", "currency_converter"), "TJS"],
            "TMT": [_("Turkmenistan Manat", "currency_converter"), _("Turkmenistan Manat", "currency_converter")],
            "TND": [_("Tunisian Dinar", "currency_converter"), _("Tunisian Dinars", "currency_converter"), "DT"],
            "TRY": [_("Turkish Lira", "currency_converter"), _("Turkish Liras", "currency_converter"), "TRY"],
            "TZN": [_("Tanzanian Shilling", "currency_converter"), _("Tanzanian Shillings", "currency_converter"), "TSh"],
            "UAH": [_("Ukrainian Hryvnia", "currency_converter"), _("Ukrainian Hryvnia", "currency_converter"), "₴"],
            "UGX": [_("Ugandan Shilling", "currency_converter"), _("Ugandan Shillings", "currency_converter"), "USh"],
            "UZS": [_("Uzbekistan So'm", "currency_converter"), _("Uzbekistan So'ms", "currency_converter"), "UZS"],
            "VEF": [_("Venezuelan Bolívar Fuerte", "currency_converter"), _("Venezuelan Bolívares Fuertes", "currency_converter"), "Bs\.F\."],
            "VND": [_("Vietnamese Đồng", "currency_converter"), _("Vietnamese Đồng", "currency_converter"), "₫"],
            "VUV": [_("Vanuatu Vatu", "currency_converter"), _("Vanuatu Vatu", "currency_converter"), "VT"],
            "XAF": [_("Central African CFA Franc", "currency_converter"), _("Central African CFA Francs", "currency_converter"), "FCFA"],
            "XAG": [_("Troy Ounce of Silver", "currency_converter"), _("Troy Ounces of Silver", "currency_converter"), "XAG"],
            "XAU": [_("Troy Ounce of Gold", "currency_converter"), _("Troy Ounces of Gold", "currency_converter"), "XAU"],
            "XDR": [_("Special Drawing Rights", "currency_converter"), _("Special Drawing Rights", "currency_converter"), "XDR"],
            "XOF": [_("West African CFA Franc", "currency_converter"), _("West African CFA Francs", "currency_converter"), "CFA"],
            "XPF": [_("CFP Franc", "currency_converter"), _("CFP Francs", "currency_converter"), "CFP"],
            "YER": [_("Yemeni Rial", "currency_converter"), _("Yemeni Rials", "currency_converter"), "YER"],
            "ZAR": [_("South African Rand", "currency_converter"), _("South African Rands", "currency_converter")],
            "ZMW": [_("Zambian Kwacha", "currency_converter"), _("Zambian Kwacha", "currency_converter"), "ZK"],
        }
    }
};